/**
 * aiParser.js
 *
 * Native AI Chatbot Agent using Groq API.
 * Key Badini phrases are HARDCODED here so the AI can never change or translate them.
 */

const axios = require('axios');
const fs = require('fs');
const path = require('path');

const GROQ_API_URL = 'https://api.groq.com/openai/v1/chat/completions';
const MODEL_NAME   = 'llama-3.3-70b-versatile';

// ─── HARDCODED BADINI PHRASES ────────────────────────────────────────────────
// These are FIXED. The AI is not allowed to rephrase them. They are injected
// directly into the reply by the code — not generated by the AI.
const PHRASES = {
  greeting:      'سلاڤ بخێرهاتی ،کەرەمکە، دێ چاوا شێم خزمەتا تە کەم 🌹',
  confirmPrompt: 'گەلەک باشە ، دەستخۆش، دوبارە ڵێنێرینێ بکە ئایا پێزانین درستن ، زور باشە ئەم یێل پێنگاڤا دوماهیکێ تە دڤێت گهورینەکێ یان تشتەکی زێدە بکەی ؟',
  orderDone:     'سوپاسیا تە دکەین بۆ دەممێ تە یێ ببها و داخازا بازارکرنەکا خوش بو هەوەیێن بەرێز دکەین ✅'
};

// ─── CUSTOM RULES (editable by the user in prompt_rules.txt) ─────────────────
const customRulesPath = path.join(__dirname, '..', 'prompt_rules.txt');
let customRules = '';
try {
  customRules = fs.readFileSync(customRulesPath, 'utf8');
} catch (err) {
  console.log('Could not load prompt_rules.txt, using defaults.');
}

// ─── SYSTEM PROMPT ────────────────────────────────────────────────────────────
const SYSTEM_PROMPT = `You are a customer service agent for an Instagram store.
You speak ONLY in Badini Kurdish. Avoid Sorani. Use Sorani ONLY if you have absolutely no Badini word.

FIXED PHRASES — use these EXACTLY, do NOT rephrase them:
- When greeting → "${PHRASES.greeting}"
- When showing order summary → end with: "${PHRASES.confirmPrompt}"
- When order is confirmed → respond with EXACTLY: "${PHRASES.orderDone}"

CATEGORY‑SPECIFIC QUESTIONS (ask only what is relevant to the product):
- Clothing / shoes / accessories → ask for Size AND Color if missing
- Electronics (phone, laptop, TV, etc.) → ask for Model / Specification (storage, color) if missing
- Perfume / beauty → ask for Fragrance or Size (ml) if missing
- Food / grocery → ask for any preference (flavor, weight) if missing
- ANY product → always ask for Quantity if missing

STRICT RULES:
1. NEVER translate product or brand names. Keep them EXACTLY as the customer wrote them.
2. Always ask ONE question at a time. Never overwhelm the customer.
3. Only ask for Size/Color if the product actually needs it.
4. Always collect: Name, Phone, Address, Product, Quantity.
5. Once you have everything, show the summary. After customer confirms, set isOrderComplete = true.

EXTRA RULES FROM STORE OWNER:
${customRules}

SUMMARY FORMAT (use this exactly):
تکایە پێداچوونێ د زانیاریێن خوە دا بکە:
📦 کاڵا: [exact product]
🔢 دانە: [quantity]
📐 قەبارە: [size if applicable]
🎨 ڕەنگ: [color if applicable]
👤 ناڤ: [name]
📱 موبایل: [phone]
📍 ناونیشان: [address]
${PHRASES.confirmPrompt}

CRITICAL: Respond ONLY with a pure JSON object — nothing else.
{
  "isGreeting": false,
  "replyToCustomer": "Your Badini message here",
  "isOrderComplete": false,
  "extractedData": {
    "customerName": "",
    "phone": "",
    "address": "",
    "product": "EXACT words used by customer — NO TRANSLATION",
    "quantity": "",
    "size": "",
    "color": ""
  }
}

Set "isGreeting" to true ONLY if the user message is purely a greeting (hi, hello, سلاڤ, مرحبا) with no order info.
Set "isOrderComplete" to true ONLY after the customer has confirmed the summary.`;

// ─── MAIN FUNCTION ────────────────────────────────────────────────────────────
async function getAIResponse(messages) {
  const apiKey = process.env.GROQ_API_KEY;

  if (!apiKey || !apiKey.startsWith('gsk_')) {
    console.warn('⚠️ GROQ_API_KEY is invalid or missing.');
    return null;
  }

  const apiMessages = [
    { role: 'system', content: SYSTEM_PROMPT },
    ...messages
  ];

  try {
    const response = await axios.post(
      GROQ_API_URL,
      {
        model: MODEL_NAME,
        messages: apiMessages,
        temperature: 0.1,
        response_format: { type: 'json_object' }
      },
      {
        headers: {
          'Authorization': `Bearer ${apiKey}`,
          'Content-Type': 'application/json'
        },
        timeout: 12000
      }
    );

    const aiText = response.data?.choices?.[0]?.message?.content;
    if (!aiText) return null;

    console.log(`🤖 AI Raw JSON:\n${aiText}`);

    const parsed = JSON.parse(aiText.trim());

    // ── HARDCODED OVERRIDE: if AI flagged this as a greeting, use our fixed phrase ──
    let reply = parsed.replyToCustomer || PHRASES.greeting;
    if (parsed.isGreeting === true) {
      reply = PHRASES.greeting;
    }

    // ── HARDCODED OVERRIDE: if order is complete, use our fixed thank-you phrase ──
    if (parsed.isOrderComplete === true) {
      reply = PHRASES.orderDone;
    }

    return {
      replyToCustomer: reply,
      isOrderComplete: !!parsed.isOrderComplete,
      extractedData: {
        customerName: (parsed.extractedData?.customerName || '').trim(),
        phone:        (parsed.extractedData?.phone        || '').trim(),
        address:      (parsed.extractedData?.address      || '').trim(),
        product:      (parsed.extractedData?.product      || '').trim(),
        quantity:     (parsed.extractedData?.quantity     || '').trim(),
        size:         (parsed.extractedData?.size         || '').trim(),
        color:        (parsed.extractedData?.color        || '').trim(),
      }
    };

  } catch (error) {
    console.error(`⚠️ Groq AI error: ${error.response?.data ? JSON.stringify(error.response.data) : error.message}`);
    return null;
  }
}

module.exports = { getAIResponse, PHRASES };
